import React, { useState, useEffect } from 'react';

function Addstaff() {
  const [formData, setFormData] = useState({
    userid: '',
    name: '',
    dob: '',
    address: '',
    phoneno: '',
    email: '',
    dept: '',
    picture: null,
    status: 'active',
    password: '',
  });

  const [isSubmitted, setIsSubmitted] = useState(false);

  useEffect(() => {
    const generatedPassword = Math.random().toString(36).slice(-8);
    setFormData((prevData) => ({
      ...prevData,
      password: generatedPassword,
    }));
  }, []);

  const handleChange = (e) => {
    const { name, value, type } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const handleFileChange = (e) => {
    setFormData((prevData) => ({
      ...prevData,
      picture: e.target.files[0],
    }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log(formData);
    setIsSubmitted(true);
  };

  return (
    <div className="p-4 max-w-sm mx-auto bg-white rounded shadow-md">
      <h2 className="text-lg font-bold mb-4">Registration Form</h2>
      {isSubmitted ? (
        <p className="text-green-500">Registration Successful!</p>
      ) : (
        <form onSubmit={handleSubmit}>
          <label className="block mb-2">
            User ID:
            <input
              type="text"
              name="userid"
              value={formData.userid}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded text-sm"
            />
          </label>
          <label className="block mb-2">
            Name:
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded text-sm"
            />
          </label>
          <label className="block mb-2">
            Date of Birth:
            <input
              type="date"
              name="dob"
              value={formData.dob}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded text-sm"
            />
          </label>
          <label className="block mb-2">
            Address:
            <input
              type="text"
              name="address"
              value={formData.address}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded text-sm"
            />
          </label>
          <label className="block mb-2">
            Phone Number:
            <input
              type="text"
              name="phoneno"
              value={formData.phoneno}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded text-sm"
            />
          </label>
          <label className="block mb-2">
            Email:
            <input
              type="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded text-sm"
            />
          </label>
          <label className="block mb-2">
            Department:
            <input
              type="text"
              name="dept"
              value={formData.dept}
              onChange={handleChange}
              className="w-full p-2 border border-gray-300 rounded text-sm"
            />
          </label>
          <label className="block mb-2">
            Picture:
            <input
              type="file"
              name="picture"
              onChange={handleFileChange}
              className="w-full p-2 border border-gray-300 rounded text-sm"
            />
          </label>
          <div className="block mb-2">
            Status:
            <label className="inline-flex items-center">
              <input
                type="radio"
                name="status"
                value="active"
                checked={formData.status === 'active'}
                onChange={handleChange}
                className="form-radio"
              />
              <span className="ml-2">Active</span>
            </label>
            <label className="inline-flex items-center ml-4">
              <input
                type="radio"
                name="status"
                value="deactive"
                checked={formData.status === 'deactive'}
                onChange={handleChange}
                className="form-radio"
              />
              <span className="ml-2">Deactive</span>
            </label>
          </div>
          <label className="block mb-2">
            Password (Autogenerated):
            <input
              type="text"
              name="password"
              value={formData.password}
              readOnly
              className="w-full p-2 border border-gray-300 rounded text-sm"
            />
          </label>
          <button
            type="submit"
            className="w-full bg-blue-500 text-white p-2 rounded mt-4 hover:bg-blue-600"
          >
            Register
          </button>
        </form>
      )}
    </div>
  );
}

export default Addstaff;
